export const routes = {
  Home: "/",
  Profile: "/profile",
  Signup: "/signup",
  Login: "/login",
  Logout: "/logout",
  Track: "/track",
  Delivery: "/delivery",
  Post: "/post",
  UpdatePost: "/updatePost/:id",
  UpdateProfile: "/update",
  Market: "/market",
  SinglePost: "/aProduct/:id",
  OtherUser: "/otherUser/:id",
  Cart: "/mycart",
  AdminUsers : "/admin",
};

export const routing = [
  "/",
  "/profile",
  "/signup",
  "/login",
  "/logout",
  "/track",
  "/delivery",
  "/post",
  "/updatePost/:id",
  "/update",
  "/market",
  "/aProduct/:id",
  "/otherUser/:id",
  "/mycart",
  "/admin",
  "/adminPosts"
];
